site_name: Ayuda Dinex
site_description: Sitio de ayuda para los usuarios de Dinex.
site_author: Dinex SpA
site_favicon: img/favicon.png
copyright: Dinex SpA - 2015
theme_dir: dinex_theme
include_next_prev: false
pages:

- Inicio: 'index.md'

- Preguntas Frecuentes:
  - 'Preguntas Generales': 'faq/FAQ-preguntas-generales.md'
  #- 'Personas': 'faq/FAQ-personas.md'
  #- 'Taxistas': 'faq/FAQ-taxistas.md'
  #- 'Problemas de Pago': 'faq/problemas.md'
  - 'Solución de Problemas': 'faq/soluciones.md'

- Guías:
  - 'Cuenta de Usuario': 'guias/cuenta.md'
  - 'Pagar & Recibir': 'guias/pagos.md'
  - 'Cargar & Retirar': 'guias/cargar-retirar.md'
  - 'Costos': 'guias/costos.md'
  - 'Seguridad': 'guias/seguridad.md'
  - 'Manual de Usuario': 'guias/manual.md'

- Condiciones:
  - 'Términos de Uso': 'legal/eula.md'
  - 'Privacidad': 'legal/privacidad.md'

- Contacto: 'solicitud.md'
